# Generated by Django 5.2.7 on 2026-03-09 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=150, null=True)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('conservation_status', models.CharField(blank=True, max_length=50)),
                ('image_sample', models.ImageField(blank=True, null=True, upload_to='species_samples/')),
            ],
        ),
        migrations.CreateModel(
            name='UnderwaterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='underwater_data/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('depth', models.FloatField(blank=True, help_text='Depth in meters', null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255)),
                ('enhanced_file', models.FileField(blank=True, null=True, upload_to='enhanced_data/')),
                ('is_processed', models.BooleanField(default=False)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShoalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoal_id', models.CharField(max_length=100)),
                ('species_count', models.IntegerField()),
                ('average_speed', models.FloatField()),
                ('movement_pattern', models.CharField(max_length=100)),
                ('analysis_date', models.DateTimeField(auto_now_add=True)),
                ('trajectory_data', models.JSONField(blank=True, null=True)),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoal_analyses', to='core.underwaterdata')),
            ],
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('box_x', models.FloatField()),
                ('box_y', models.FloatField()),
                ('box_w', models.FloatField()),
                ('box_h', models.FloatField()),
                ('frame_number', models.IntegerField(default=0)),
                ('timestamp_offset', models.FloatField(default=0.0)),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.species')),
                ('data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='core.underwaterdata')),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('summary', models.TextField()),
                ('pdf_report', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('csv_report', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.underwaterdata')),
            ],
        ),
    ]
